"""Create tables for auth service

Revision ID: 4e54f0a958de
Revises: 
Create Date: 2024-02-14 16:38:33.089337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e54f0a958de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(length=128), nullable=True),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_service'
    )
    op.create_index(op.f('ix_auth_service_users_username'), 'users', ['username'], unique=True, schema='auth_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_service_users_username'), table_name='users', schema='auth_service')
    op.drop_table('users', schema='auth_service')
    # ### end Alembic commands ###
